A few fixups

diff --git a/fire/cookie b/fire/cookie
--- a/fire/cookie
+++ b/fire/cookie
@@ -1,12 +1,4 @@
 #!/bin/bash
-# -*- mode:sh -*-
-
-die() {
-    echo >&2 "$*"
-    exit 1
-}
-
-
 
 cleanup() {
     rm -f "$tmpfile"
@@ -14,42 +6,24 @@ cleanup() {
 trap cleanup  EXIT INT QUIT TERM
 
 # Run older ld (pseudo condition)
-
-if [ "$#" == "0" ];  then
-    profile=default
-elif [ "$#" == "1"  ]; then
-    profile=$1
-else
-    die "usage $0 [profile]"
-fi;
-
+profile=default
 
 extract_cookies() {
+  sqlfile=$(ls -t "/Users/dave/Library//Application Support/Firefox/Profiles/yw78w5ho.default/cookies.sqlite" | head -1)
 
-if [ "$#" -ge 1 ]; then
-    sqlfile="$1"
-else
-    if tty -s; then
-    sqlfile=$(ls -t "/Users/dave/Library//Application Support/Firefox/Profiles/yw78w5ho.default/cookies.sqlite" | head -1)
+  if [ "$sqlfile" != "-" -a ! -r "$sqlfile" ]; then
+      echo "Error. File $sqlfile is not readable." >&2
+      exit 1
+  fi
 
-    sqlfile="-"     # Will use 'cat' below to read stdin
-    fi
-fi
+  # We have to copy cookies.sqlite, because FireFox has a lock on it
+  cat "$sqlfile" >> $tmpfile
 
-if [ "$sqlfile" != "-" -a ! -r "$sqlfile" ]; then
-    echo "Error. File $sqlfile is not readable." >&2
-    exit 1
-fi
+  # This is the format of the sqlite database:
+  # CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, name TEXT, value TEXT, host TEXT, path TEXT,expiry INTEGER, lastAccessed INTEGER, isSecure INTEGER, isHttpOnly INTEGER);
 
-# We have to copy cookies.sqlite, because FireFox has a lock on it
-cat "$sqlfile" >> $tmpfile
-
-
-# This is the format of the sqlite database:
-# CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, name TEXT, value TEXT, host TEXT, path TEXT,expiry INTEGER, lastAccessed INTEGER, isSecure INTEGER, isHttpOnly INTEGER);
-
-echo "# Netscape HTTP Cookie File"
-sqlite3 -separator $'\t' $tmpfile <<- EOF
+  echo "# Netscape HTTP Cookie File"
+  sqlite3 -separator $'\t' $tmpfile <<- EOF
 .mode tabs
 .header off
 select host,
@@ -62,15 +36,11 @@ value
 from moz_cookies;
 EOF
 
-cleanup
+  cleanup
 
 }
 
 tmpfile="$(mktemp /tmp/cookies.sqlite.XXXXXXXXXX)"
 curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"
 
-echo "/Users/dave/Library//Application Support/Firefox/Profiles/yw78w5ho.default/cookies.sqlite" | { read cookie_file ;
-extract_cookies "$cookie_file" ;
-}
-
-
+extract_cookies
